name: Lint

on:
  push:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftLint
        uses: cirruslabs/swiftlint-action@v1
        with:
          version: latest
      - name: Run swift-format
        run: |
          xcrun swift-format lint . \
          --parallel \
          --recursive \
          --strict
